Update trivy-scan.yaml

diff --git a/.github/workflows/trivy-scan.yaml b/.github/workflows/trivy-scan.yaml
--- a/.github/workflows/trivy-scan.yaml
+++ b/.github/workflows/trivy-scan.yaml
@@ -9,7 +9,7 @@ on:
 
 permissions:
   contents: read
-  security-events: write
+  pull-requests: write
 
 env:
   TRIVY_CACHE_DIR: /tmp/trivy-cache
@@ -25,6 +25,9 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install -y jq
+
       - name: Cache Trivy DB
         uses: actions/cache@v4
         with:
@@ -35,18 +38,59 @@ jobs:
 
       - name: Run Trivy Scan (Vuln, Secret, Misconfig, License)
         uses: aquasecurity/trivy-action@v0.36.0
+        continue-on-error: true
         with:
           version: v0.71.0
           scan-type: fs
           scanners: vuln,secret,misconfig,license
           trivy-config: trivy.yaml
-          format: sarif
-          output: trivy-results.sarif
+          format: json
+          output: trivy-results.json
           exit-code: 1
 
-      - name: Upload Trivy SARIF to GitHub Security
-        if: always()
-        uses: github/codeql-action/upload-sarif@v4
+      
+      - name: Extract Trivy summary
+        id: summary
+        run: |
+          CRITICAL=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="CRITICAL")] | length' trivy-results.json)
+          HIGH=$(jq '[.Results[].Vulnerabilities[]? | select(.Severity=="HIGH")] | length' trivy-results.json)
+
+          echo "critical=$CRITICAL" >> $GITHUB_OUTPUT
+          echo "high=$HIGH" >> $GITHUB_OUTPUT
+
+      
+      - name: Comment PR with Trivy summary
+        if: github.event_name == 'pull_request'
+        uses: marocchino/sticky-pull-request-comment@v2
         with:
-          sarif_file: trivy-results.sarif
-          category: trivy-iac
+          header: trivy-scan
+          message: |
+            🔒 **Trivy Security Scan Result**
+            
+              Critical: ${{ steps.summary.outputs.critical }}
+              High: ${{ steps.summary.outputs.high }}
+
+            🚨 Please fix vulnerabilities before merging.
+            
+            📦 Full report is available in workflow artifacts.
+
+        
+      - name: Upload Trivy report
+        uses: actions/upload-artifact@v4
+        with:
+          name: trivy-report
+          path: trivy-results.json
+
+      - name: Fail if vulnerabilities found
+        run: |
+            if [ "${{ steps.summary.outputs.critical }}" -gt 0 ] || [ "${{ steps.summary.outputs.high }}" -gt 0 ]; then   # ✅ CHANGED
+              echo "❌ Failing due to HIGH/CRITICAL vulnerabilities"
+              exit 1
+            fi
+
+      # - name: Upload Trivy SARIF to GitHub Security
+      #   if: always()
+      #   uses: github/codeql-action/upload-sarif@v4
+      #   with:
+      #     sarif_file: trivy-results.sarif
+      #     category: trivy-iac
